#%RAML 1.0 DataType

type: array
items:
  type: object
  properties:
    Name:
      type: string
      required: true    
    Phone:
      type: string
      required: true      
    BillingStreet:
      type: string
      required: true      
    BillingCity:
      type: string
      required: true      
    BillingState:
      type: string
      required: true      
    BillingPostalCode:
      type: string
      required: true      
    BillingCountry:
      type: string
      required: true      
  