#%RAML 1.0 SecurityScheme
type: OAuth 2.0

describedBy:
  headers:
    Authorization: 
      description: used to send a valid oAuth2 token
      type: string
  responses:
    401:
      description: Unautherized
    403:
      description: Forbiden
  